webdriver {
  driver = edge
}
serenity {
  project.name = "Reto Serenity Screenplay"
}

webdriver{
compabilities{
"goog:ChromeOptions"{
args = ["satrt-maximized","tets-type","no-sandox","disable-popup-blocking"]
}
}
}