webdriver {
  driver = chrome

  capabilities {

    browserName = "chrome"

    "goog:chromeOptions" {

      args = [
        "--disable-notifications",
        "--disable-popup-blocking",
        "--disable-infobars",
        "--no-default-browser-check",
        "--disable-features=PasswordManagerOnboarding",
        "--disable-features=PasswordLeakDetection"
      ]

      prefs {
        credentials_enable_service = false
        profile.password_manager_enabled = false
      }
    }
  }
}